name: "BedwarsRel"
description: |
  §aBedwars Reloaded - Minecraft护床战争插件!
  §7护床战争是一个Minecraft小游戏，队伍(最多15个)试图摧毁其他队伍的床。但还有更多内容：在整个地图上都有资源生成器生成物品。有些物品比其他物品更有价值，你可以用这些物品在所谓的"村民商店"中购买不同的东西。你会发现强大的武器或药水或简单的方块来到达其他基地。到达其他基地？是的，每个队伍都从一个岛屿开始，你必须用在"村民商店"中购买的方块到达其他队伍。当你遇到敌人时，你必须尝试杀死他，这样他就会失去库存中的所有装备。一旦一个队伍的床被摧毁，他们就无法再次重生，最后存活的队伍获胜。
author: "不穿胖次の小奶猫"
website: "https://github.com/NyaNyagulugulu/NekoBedwarsRel"

main: io.github.bedwarsrel.BedwarsRel
version: ${versionstring}

awareness:
    - !@UTF8

depend: []
softdepend: [Multiverse-Core, Multiworld, MultiWorld, HolographicDisplays, HologramAPI, UltimateCore]

commands:
    bw:
        description: 所有测试插件命令的基础命令
        usage: /<command> help
        permission: bw.base
    bw setspawner:
        description: 设置特定类型的资源生成点
        usage: /<command> [游戏] [资源]
        permission: bw.setup
    bw addgame:
        description: 添加一个新游戏
        usage: /<command> [名称]
        permission: bw.setup
    bw start:
        description: 开始一个游戏
        usage: /<command> [游戏]
        permission: bw.setup
    bw addteam:
        description: 向游戏中添加一个队伍
        usage: /<command> [名称] [颜色]
        permission: bw.setup
    bw save:
        description: 将游戏保存到配置文件
        usage: /<command> [名称]
        permission: bw.setup
    bw setregion:
        description: 设置游戏的两个可能区域之一
        usage: /<command> [名称] [loc1;loc2]
        permission: bw.setup
    bw join:
        description: 加入游戏中的特定队伍
        usage: /<command> [游戏] [队伍]
        permission: bw.base
    bw setspawn:
        description: 设置队伍的出生点
        usage: /<command> [游戏] [队伍]
        permission: bw.setup
    bw setlobby:
        description: 设置游戏的大厅位置
        usage: /<command> [游戏]
        permission: bw.setup
    bw settarget:
        description: 设置游戏中队伍的床
        usage: /<command> [游戏] [队伍]
        permission: bw.setup
    bw setbed:
        description: 设置游戏中队伍的床
        usage: /<command> [游戏] [队伍]
        permission: bw.setup
    bw leave:
        description: 离开当前游戏
        usage: /<command>
        permission: bw.base
    bw reload:
        description: 重新加载配置和翻译
        usage: /<command>
        permission: bw.setup
    bw list:
        description: 列出所有可用游戏
        usage: /<command>
        permission: bw.base
    bw regionname:
        description: 设置区域名称
        usage: /<command>
        permission: bw.setup
    bw removeteam:
        description: 从游戏中移除一个队伍
        usage: /<command>
        permission: bw.setup
    bw removegame:
        description: 移除一个游戏
        usage: /<command>
        permission: bw.setup
    bw clearspawner:
        description: 从游戏中移除所有资源生成器
        usage: /<command>
        permission: bw.setup
    bw gametime:
        description: 设置游戏中使用的世界时间
        usage: /<command>
        permission: bw.setup
    bw stats:
        description: 显示护床战争统计数据
        usage: /<command>
        permission: bw.base
    bw setminplayers:
        description: 设置游戏的最小玩家数量
        usage: /<command>
        permission: bw.setup
    bw setgameblock:
        description: 为特定游戏设置目标方块
        usage: /<command>
        permission: bw.setup
    bw setbuilder:
        description: 设置地图的地图建造者，用于游戏开始时显示标题
        usage: /<command>
        permission: bw.setup
    bw setautobalance:
        description: 当全局自动平衡关闭时，开启或关闭此游戏的自动平衡
        usage: /<command>
        permission: bw.setup
    bw kick:
        description: 从游戏中踢出玩家
        usage: /<command>
        permission: bw.kick
    bw addteamjoin:
        description: 标记可用于加入特定队伍的生物
        usage: /<command>
        permission: bw.setup
    bw addholo:
        description: 添加全息统计数据的位置
        usage: /<command>
        permission: bw.setup
    bw removeholo:
        description: 移除全息统计位置
        usage: /<command>
        permission: bw.setup
permissions:
    bw.base:
        description: 允许你显示游戏
        default: true
    bw.setup:
        description: 允许你设置新游戏或现有游戏
        default: op
    bw.kick:
        description: 允许玩家从游戏中踢出其他玩家
        default: op
    bw.vip.*:
        description: 允许特殊用户权限
        default: op
        children:
            bw.vip.joinfull: true
            bw.vip.forcestart: true
            bw.vip.reducecountdown: true
            bw.vip.skipbalance: true
    bw.cmd:
        description: 允许在游戏中执行非护床战争命令
        default: op
    bw.otherstats:
        description: 允许显示其他玩家的统计数据
        default: op
